"""rename department

Revision ID: 02ef0a6d36dc
Revises: e98b16b086be
Create Date: 2024-07-06 21:43:27.576546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ef0a6d36dc'
down_revision = 'e98b16b086be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
